get_com_1<-function(train,train_d,alpha,beta,x){
  K<-length(alpha)
  alpha_matrix<-train_d%*%t(alpha)
  beta_matrix<-train_d%*%t(beta)+(1-train_d)%*%t(rep(1,K))
  xi_cov<-cor((train-alpha_matrix)/beta_matrix)
  mu_n<-rep(0,K)
  mu_d<-alpha
  sigma_n<-xi_cov
  sigma_d<-beta%*%t(beta)*xi_cov
  com<-diag(x%*%(pd.solve(sigma_n)-pd.solve(sigma_d))%*%t(x))+2*as.vector((t(mu_d)%*%pd.solve(sigma_d)-t(mu_n)%*%pd.solve(sigma_n))%*%t(x))+t(mu_n)%*%pd.solve(sigma_n)%*%mu_n-t(mu_d)%*%pd.solve(sigma_d)%*%mu_d-log(det(sigma_d)/det(sigma_n))
  com
}
